/**
 * Scans src/ for static Iconify icon names (icon="prefix:name") and generates
 * src/lib/icon-bundle.generated.ts, which registers just those icons via
 * addCollection() so <Icon ssr> renders them in server HTML with no pop-in.
 *
 * Icons not found here (dynamic names, missing sets) fall back to the runtime
 * Iconify API, so a stale bundle degrades to pop-in, never a broken icon.
 *
 * Run: bun run generate:icons
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { getIcons } from "@iconify/utils";
import type { IconifyJSON } from "@iconify/types";

const SRC_DIR = join(import.meta.dir, "..", "src");
const OUT_FILE = join(SRC_DIR, "lib", "icon-bundle.generated.ts");
const ICON_PATTERN = /icon="([a-z0-9-]+):([a-z0-9-]+)"/g;

function collectSourceFiles(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...collectSourceFiles(path));
    else if (/\.(ts|tsx)$/.test(entry.name)) files.push(path);
  }
  return files;
}

const iconsByPrefix = new Map<string, Set<string>>();
for (const file of collectSourceFiles(SRC_DIR)) {
  const source = readFileSync(file, "utf8");
  for (const [, prefix, name] of source.matchAll(ICON_PATTERN)) {
    if (!iconsByPrefix.has(prefix)) iconsByPrefix.set(prefix, new Set());
    iconsByPrefix.get(prefix)!.add(name);
  }
}

const collections: string[] = [];
let totalIcons = 0;
const warnings: string[] = [];

for (const prefix of [...iconsByPrefix.keys()].sort()) {
  const names = [...iconsByPrefix.get(prefix)!].sort();
  let setData: IconifyJSON;
  try {
    setData = JSON.parse(
      readFileSync(
        join(
          import.meta.dir,
          "..",
          "node_modules",
          "@iconify-json",
          prefix,
          "icons.json",
        ),
        "utf8",
      ),
    );
  } catch {
    console.error(
      `Missing icon set "${prefix}" — run: bun add -d @iconify-json/${prefix}`,
    );
    process.exit(1);
  }

  const subset = getIcons(setData, names, true)!;
  if (subset.not_found?.length) {
    warnings.push(
      `Not in "${prefix}" set (will use runtime API): ${subset.not_found.join(", ")}`,
    );
    delete subset.not_found;
  }
  totalIcons += Object.keys(subset.icons).length;
  collections.push(`addCollection(${JSON.stringify(subset)});`);
}

const output = `// AUTO-GENERATED by scripts/generate-icon-bundle.ts — do not edit.
// Regenerate with: bun run generate:icons
// Registers every statically referenced icon so <Icon ssr> renders on the server.
import { addCollection } from "@iconify/react";

${collections.join("\n\n")}
`;

writeFileSync(OUT_FILE, output);
for (const warning of warnings) console.warn(`⚠ ${warning}`);
console.log(
  `Wrote ${OUT_FILE} — ${totalIcons} icons from ${iconsByPrefix.size} sets.`,
);
